/// Centralized car reference data for registration and dropdowns.
/// Makes, models, colors, and years used across the app.
/// Updated for the Australian market.
class CarDataService {
  CarDataService._();

  static const List<String> carMakes = [
    'Toyota',
    'Mazda',
    'Ford',
    'Hyundai',
    'Mitsubishi',
    'Kia',
    'Honda',
    'Nissan',
    'Subaru',
    'Volkswagen',
    'Holden',
    'Mercedes-Benz',
    'BMW',
    'Audi',
    'Lexus',
    'Isuzu',
    'MG',
    'Suzuki',
    'Jeep',
    'Land Rover',
    'Volvo',
    'Peugeot',
    'Renault',
    'Tesla',
    'BYD',
    'GWM',
    'Haval',
    'LDV',
    'Jaecoo',
    'Omoda',
    'Chery',
    'RAM',
    'Chevrolet',
    'Porsche',
    'Jaguar',
    'Mini',
    'Skoda',
    'Ssangyong',
    'Genesis',
    'Cupra',
    'Ferrari',
    'Lamborghini',
    'Maserati',
    'Aston Martin',
    'Bentley',
    'Rolls-Royce',
    'Cadillac',
    'GMC',
    'Infiniti',
    'Alfa Romeo',
    'Polestar',
    'Lotus',
    'Rivian',
    'Lucid',
    'NIO',
    'XPeng',
    'Zeekr',
    'Jetour',
    'Geely',
    'Changan',
    'JAC',
    'Hongqi',
  ];

  static const Map<String, List<String>> carModels = {
    'Toyota': [
      'Corolla',
      'Camry',
      'RAV4',
      'Hilux',
      'Land Cruiser',
      'Prado',
      'Yaris',
      'C-HR',
      'Kluger',
      'Fortuner',
      '86',
      'GR Supra',
      'HiAce',
      'Granvia',
      'Corolla Cross',
      'bZ4X',
      'Crown',
    ],
    'Mazda': [
      'Mazda3',
      'Mazda2',
      'CX-3',
      'CX-5',
      'CX-30',
      'CX-9',
      'CX-60',
      'CX-8',
      'MX-5',
      'BT-50',
      'Mazda6',
    ],
    'Ford': [
      'Ranger',
      'Everest',
      'Puma',
      'Escape',
      'Mustang',
      'Focus',
      'Fiesta',
      'Territory',
      'Mondeo',
      'EcoSport',
      'F-150',
    ],
    'Hyundai': [
      'i30',
      'Tucson',
      'Santa Fe',
      'Kona',
      'Venue',
      'Palisade',
      'Ioniq 5',
      'Ioniq 6',
      'Elantra',
      'Sonata',
      'Staria',
      'iLoad',
      'iMax',
    ],
    'Mitsubishi': [
      'Outlander',
      'ASX',
      'Eclipse Cross',
      'Pajero Sport',
      'Triton',
      'Pajero',
      'Mirage',
      'Lancer',
      'Express',
    ],
    'Kia': [
      'Sportage',
      'Seltos',
      'Sorento',
      'Carnival',
      'Stonic',
      'Picanto',
      'Cerato',
      'Niro',
      'EV6',
      'EV9',
      'Rio',
    ],
    'Honda': [
      'Civic',
      'CR-V',
      'HR-V',
      'ZR-V',
      'Accord',
      'City',
      'Jazz',
      'Odyssey',
    ],
    'Nissan': [
      'X-Trail',
      'Qashqai',
      'Navara',
      'Patrol',
      'Pathfinder',
      'Juke',
      'Leaf',
      'Micra',
      'Altima',
    ],
    'Subaru': [
      'Outback',
      'Forester',
      'XV',
      'Impreza',
      'WRX',
      'Levorg',
      'BRZ',
      'Liberty',
    ],
    'Volkswagen': [
      'Golf',
      'Polo',
      'Tiguan',
      'Amarok',
      'Passat',
      'T-Cross',
      'T-Roc',
      'Touareg',
      'Multivan',
      'Caddy',
      'Arteon',
    ],
    'Holden': [
      'Commodore',
      'Colorado',
      'Trailblazer',
      'Captiva',
      'Cruze',
      'Barina',
      'Astra',
      'Trax',
    ],
    'Mercedes-Benz': [
      'A-Class',
      'C-Class',
      'E-Class',
      'S-Class',
      'GLA',
      'GLB',
      'GLC',
      'GLE',
      'GLS',
      'G-Class',
      'CLA',
      'EQA',
      'EQB',
      'EQC',
      'EQE',
      'EQS',
    ],
    'BMW': [
      '1 Series',
      '2 Series',
      '3 Series',
      '4 Series',
      '5 Series',
      '7 Series',
      '8 Series',
      'X1',
      'X2',
      'X3',
      'X4',
      'X5',
      'X6',
      'X7',
      'iX',
      'i4',
      'i7',
      'Z4',
    ],
    'Audi': [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Q2',
      'Q3',
      'Q4 e-tron',
      'Q5',
      'Q7',
      'Q8',
      'e-tron',
      'TT',
    ],
    'Lexus': ['IS', 'ES', 'LS', 'UX', 'NX', 'RX', 'LX', 'LC', 'RZ'],
    'Isuzu': ['D-Max', 'MU-X'],
    'MG': ['MG3', 'MG4', 'MG5', 'ZS', 'HS', 'RX5', 'Cyberster', 'ZST'],
    'Suzuki': [
      'Swift',
      'Vitara',
      'S-Cross',
      'Jimny',
      'Ignis',
      'Baleno',
      'Alto',
    ],
    'Jeep': [
      'Wrangler',
      'Cherokee',
      'Grand Cherokee',
      'Compass',
      'Gladiator',
      'Renegade',
    ],
    'Land Rover': [
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Range Rover',
      'Range Rover Sport',
      'Range Rover Evoque',
      'Range Rover Velar',
    ],
    'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'S90', 'V60', 'V90', 'C40'],
    'Peugeot': ['208', '2008', '3008', '5008', '308', '508'],
    'Renault': ['Clio', 'Megane', 'Captur', 'Koleos', 'Trafic'],
    'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X'],
    'BYD': [
      'Atto 3',
      'Dolphin',
      
      'Seal',
      'Seal U',
      'Sealion 6',
      'Sealion 7',
      'Shark 6',
    ],
    'GWM': [
      'Haval Jolion',
      'Haval H6',
      'Ora',
      'Tank 300',
      'Tank 500',
      'Cannon',
      'Cannon Alpha',
      'Ora Sport',
    ],
    'Haval': ['Jolion', 'H6', 'H6 GT'],
    'LDV': [
      'D90',
      'T60',
      'Deliver 9',
      'eDeliver 9',
      'eDeliver 7',
      'G10',
      'Mifa 9',
    ],
    'Jaecoo': ['J5', 'J6', 'J7', 'J8', 'J9'],
    'Omoda': ['C5', 'E5'],
    'Chery': ['Tiggo 4 Pro', 'Tiggo 7 Pro', 'Tiggo 8 Pro'],
    'RAM': ['1500', '2500', '3500'],
    'Chevrolet': ['Silverado', 'Camaro', 'Corvette'],
    'Porsche': [
      '911',
      'Taycan',
      'Panamera',
      'Macan',
      'Cayenne',
      'Cayman',
      'Boxster',
    ],
    'Jaguar': ['XE', 'XF', 'F-Pace', 'E-Pace', 'I-Pace', 'F-Type'],
    'Mini': ['Cooper', 'Countryman', 'Clubman'],
    'Skoda': [
      'Fabia',
      'Scala',
      'Octavia',
      'Superb',
      'Kamiq',
      'Karoq',
      'Kodiaq',
    ],
    'Ssangyong': ['Korando', 'Musso', 'Rexton'],
    'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
    'Cupra': ['Formentor', 'Leon', 'Ateca', 'Born', 'Tavascan'],
    'Ferrari': [
      '296 GTB',
      'SF90 Stradale',
      'F8 Tributo',
      'Roma',
      'Portofino M',
      'Purosangue',
      '812 Superfast',
    ],
    'Lamborghini': ['Urus', 'Huracán', 'Revuelto', 'Aventador', 'Temerario'],
    'Maserati': [
      'Grecale',
      'Levante',
      'Ghibli',
      'Quattroporte',
      'GranTurismo',
      'MC20',
    ],
    'Aston Martin': ['Vantage', 'DB11', 'DBS', 'DBX', 'Valhalla', 'DB12'],
    'Bentley': ['Bentayga', 'Continental GT', 'Flying Spur'],
    'Rolls-Royce': ['Phantom', 'Ghost', 'Cullinan', 'Spectre'],
    'Cadillac': ['Escalade', 'Lyriq', 'CT4', 'CT5', 'XT4', 'XT5', 'XT6'],
    'GMC': ['Sierra', 'Yukon', 'Hummer EV', 'Terrain', 'Acadia'],
    'Infiniti': ['Q50', 'Q60', 'QX50', 'QX55', 'QX60', 'QX80'],
    'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale'],
    'Polestar': ['2', '3', '4'],
    'Lotus': ['Emira', 'Eletre', 'Evija', 'Emeya'],
    'Rivian': ['R1T', 'R1S'],
    'Lucid': ['Air', 'Gravity'],
    'NIO': ['ET5', 'ET7', 'EL6', 'EL7', 'ES8'],
    'XPeng': ['P7', 'G9', 'G6'],
    'Zeekr': ['001', 'X', '009'],
    'Jetour': ['Dashing', 'X70', 'X90', 'T2'],
    'Geely': ['Coolray', 'Azkarra', 'Monjaro', 'Tugella'],
    'Changan': ['CS35 Plus', 'CS75 Plus', 'UNI-K', 'UNI-T', 'UNI-V'],
    'JAC': ['JS4', 'JS6', 'J7', 'T8'],
    'Hongqi': ['E-HS9', 'H5', 'H9', 'HS5'],
  };

  static const List<String> carColors = [
    'Black',
    'White',
    'Silver',
    'Grey',
    'Dark Grey',
    'Red',
    'Maroon',
    'Blue',
    'Navy Blue',
    'Green',
    'Olive',
    'Brown',
    'Beige',
    'Yellow',
    'Orange',
    'Purple',
    'Gold',
    'Pearl White',
    'Metallic Blue',
    'Graphite',
    'Bronze',
    'Champagne',
  ];

  /// Years from 1980 to current year.
  static List<String> get carYears => List.generate(
    DateTime.now().year - 1979,
    (index) => (DateTime.now().year - index).toString(),
  );
}
